#!/bin/sh

# readall - pass all files to stdin of a command - version 0.1.0 - 2008-05-30
#
# Copyright (C) 2001-2008 Benoit Dolez & Willy Tarreau
#       mailto: benoit@ant-computing.com,willy@ant-computing.com
#
# This program is licenced under GPLv2 ( http://www.gnu.org/licenses/gpl.txt )

# This script reads all files in the specified directory, or the specified file,
# decompresses any gzip/bzip2 file, and extract any existing tar archive, then
# pass the resulting stream to the stdin of a command specified on the command
# line. The command is executed once per file or archive. This is specifically
# designed to be used with the patch command.

cmd_bzip2=${cmd_bzip2:-bzip2}
cmd_gzip=${cmd_gzip:-gzip}
cmd_tar=${cmd_tar:-tar}
cmd_cat=${cmd_cat:-cat}

if [ $# -lt 2 ]; then
	echo "Usage: ${0##*/} <dir|file.{|gz|bz2|tar|tgz|tar.bz2}> cmd [args...]" >&2
	echo "       Will extract files to stdin of command <cmd>." >&2
	echo "       Typical use is :" >&2
	echo "       ${0##*/} patches-2.1.3 patch -p1" >&2
	echo "       ${0##*/} patches.tgz patch -p1" >&2
	exit 1
fi

if [ -d "$1/." ]; then
    list=( "$1"/* )
elif [ -e "$1" ]; then
    list=( "$1" )
else
    echo "FATAL: \"$1\" does not exist." >&2
    exit 1
fi
shift

for p in "${list[@]}"; do
	if [ -s "$p" ]; then
		case "$p" in
		*.tar.bz2|*.tbz2|*.tbz)
			${cmd_bzip2} -cd "$p" | ${cmd_tar} -xOf - | "$@"
			;;
		*.tar.gz|*.tgz)
			${cmd_gzip} -cd "$p" | ${cmd_tar} -xOf - | "$@"
			;;
		*.tar)
			${cmd_tar} xOf "$p" | "$@"
			;;
		*bz2)
			${cmd_bzip2} -cd "$p" | "$@"
			;;
		*gz)
			${cmd_gzip}  -cd "$p" | "$@"
			;;
		*)
			${cmd_cat} "$p" | "$@"
			;;
		esac
	else
		echo "WARNING: file \"$p\" is empty." >&2
	fi
done
